# Generated by Django 6.0 on 2025-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Banned')], default=1),
        ),
    ]
