# Generated by Django 6.0 on 2025-12-25 10:55

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    RoleModel = apps.get_model('users', 'Role')
    role_names = ('customer', 'admin', 'vendor', 'visitor')
    for role_name in role_names:
        RoleModel.objects.create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles)
    ]
