# Generated by Django 6.0 on 2026-01-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
