# Generated by Django 6.0 on 2026-01-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car',
        ),
    ]
