# Generated by Django 6.0 on 2026-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('base_duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('service_type', models.IntegerField(choices=[(1, 'Periodic'), (2, 'Mechanical'), (3, 'Body/Paint'), (4, 'Detailing')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
